{% set name = "SDL2_gfx" %}
{% set version = "1.3.0" %}
{% set sha256 = "9843924d46eacbabba685a239cf2284b948766a20ef2caa48cb18462a3295caf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.ferzkopp.net/Software/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - sdl2
    - toolchain

  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - sdl2

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - test -f $PREFIX/lib/libSDL2_gfx.a  # [unix]
    - test -f $PREFIX/lib/libSDL2_gfx.dylib  # [osx]
    - test -f $PREFIX/lib/libSDL2_gfx.so  # [linux]
    - if not exist %PREFIX%\\Library\\lib\\SDL2_gfx.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\SDL2_gfx.dll exit 1  # [win]

about:
  home: http://www.ferzkopp.net/wordpress/2016/01/02/sdl_gfx-sdl2_gfx/
  license: ZLIB
  license_file: COPYING
  summary: "Graphics primitives and surface functions for SDL2"
  description: |
    The SDL2_gfx library provides the basic drawing functions such as lines, 
    circles or polygons provided by SDL_gfx on SDL2 against renderers of SDL2.
  doc_url: http://www.ferzkopp.net/Software/SDL2_gfx/Docs/html/index.html
  dev_url: https://sourceforge.net/projects/sdl2gfx/

extra:
  recipe-maintainers:
    - dschreij
