travis:
  secure:
    BINSTAR_TOKEN: QlrBcpeL1m+qdL/2VY7t7xShwoHIqcdXBxUA1fd67G0mO4o7g+WJeLt6ElRCaFY067Sr73Al9Uw11kqjWBQTENmisZE6ue/nikZeG7eBhXSgjVqg5QZzbMcwXGnOK4+5X4/ZnXHr9OIp8AVPqfelUC2/pxvooPoJGoT3ppJIQDaDC3tuDi6fLUsKnriQ+puPOcjyR04ccnhNQ4fpvS/+WZrMpYJGTdsRbBMpOX5Sb3XVzUFxaZqtapOQZg4WpxloJgc9rsK+m7KxlBZ09Nv7U7xPmK8mbzt901oGA/Is09F7W/ASYP7RdOO9381Q17jAOlvMkFjzP0s4r6aW/R71kFbGNQ9dfUyqgUVBJSflMn+ScqegcbGg0UChFCxZ6jKZmSuh2CQrdwbVIPhCQwqAXhOsi6j4ka4iXcnqBtdUsZwE997R/e1mskBZVor07dJY7MYdEcW6cLKpy4U8mtQ4NVfAhe6g73r3k2gamXrs7cr9qk1Ns5oD1cMFYbwTQym1cUSTE+2ThryEcS+U2FV0gKyTaMGaI5pTEWTc9OzgQskNhZDnrFE2bBjXe8LphFtylSO8TqH/NsTNWuiOk0URc6hLJugZ3tyLloGEP3jGgXGIjKvTAZfFrYro3v0dtxlcenkVkhg1dEtvV2QtA+okYvs+gvpUUS4e83+oaT3TfMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
