travis:
  secure:
    BINSTAR_TOKEN: csIl7H654gJxCBjHlXQVS9frT5/MWeTA/iMvi2A2bExzhz/7HI4KibLKTu295TeX9OPjEND05RsleXA/m1K8fF766LohbqlnMSWDbJ14XlHvPN+7sg9vfbU+wlmUc2ZSjr8zMsLLCM83z6r7nl1taKZEZF5tU2u7eUG1m+67CQniDS85J0LShhei7cO7JRT1mmhmFw4l9ewFv+qSY1N0gQOtmvM3oGOz7ZxHQPvw+wVJyVCCs8Rv20pD2YjKPnjgvRY2UX12NpXL12D5To3iHwZE7sqyw/AcN5BBJwYYDJZm4pvkv/l/mDtX4PLthO3o3w0/OCM9Zob4demmVCtsGNAYuhZaonkV2XVDw3yc31d2wH//xDabYyYs0XjvMsjUhM5HHq1Mmz3MZR/illTGGAvatBqhVHWdqOweR09765q5qt2ocVrLle0I/SnQbmCmMyulo97cpNXMOxABKZRm1gzXnyz2osqIu9abB1KI4u2K6aBwEUQpJna5IyhIK4LMGHAy7clwH8XGDEQIQwl+NxJD6cH1+Gq9HXlQTo65B8pXy49t/QSHBjJu5TbgMdzIn1fvmZ6Ka5Rjk0sprbNqvzr8ZUkWu30umKVrlv2XhHxO+gMXpftL14VmKBTzucCwZcnNuxsj8sS/OzZzv9VC/yz17cgsh+TNv8N36ZHTs3A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
